# -*- coding: utf-8 -*-
"""Project 128.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Iu__xnRSUguFbb9TnQ14zpyHglIYEQX
"""

import pandas as pd
import numpy as np
import csv
import requests

from bs4 import BeautifulSoup as bs

link_url = "https://en.wikipedia.org/wiki/List_of_brown_dwarfs"
link_data = requests.get(link_url)

print(link_data)

soup = bs(link_data.text, "html.parser")

link_table = soup.find("table")

temp_list = []

table_rows = link_table.find_all("tr")


for tr in table_rows:
    td = tr.find_all('td')
    row = [i.text.rstrip() for i in td]
    temp_list.append(row)

Name = []
Distance = []
Mass = []
Radius = []

for i in range(1, len(temp_list)):
  Name.append(temp_list[i][0])
  Distance.append(temp_list[i][5])
  Mass.append(temp_list[i][7])
  Radius.append(temp_list[i][8])
  
df = pd.DataFrame(list(zip(Name, Distance, Mass, Radius)), columns = ["Star_Name", "Distance", "Mass", "Radius"])
print(df)

df.to_csv("List_of_brown_dwarfs.csv")